CREATE TABLE trunks (
    id              INTEGER PRIMARY KEY,
    name            TEXT    NOT NULL,
    type            TEXT    NOT NULL,
    enabled         BOOLEAN DEFAULT 1,
    host            TEXT,
    port            INTEGER DEFAULT 5060,
    transport       TEXT    DEFAULT 'udp',
    username        TEXT,
    password        TEXT,
    auth_username   TEXT,
    register_expiry INTEGER DEFAULT 300,
    remote_hosts    TEXT,
    local_host      TEXT,
    codecs          TEXT,
    max_channels    INTEGER DEFAULT 0,
    caller_id_name  TEXT,
    caller_id_num   TEXT,
    prefix_strip    INTEGER DEFAULT 0,
    prefix_add      TEXT    DEFAULT '',
    priority        INTEGER DEFAULT 10,
    created_at      DATETIME DEFAULT (datetime('now')),
    updated_at      DATETIME DEFAULT (datetime('now'))
);
